name: Flexible AWS Deployment

on:
  workflow_dispatch:
    inputs:
      environment_name:
        description: 'AWS Environment Name'
        required: true
        default: 'Flutterbye-env'
        type: string
      application_name:
        description: 'AWS Application Name'
        required: true
        default: 'FlutterBye'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Create deployment package
      run: |
        zip -r flutterbye-deployment.zip . \
          -x "*.git*" \
          -x "*node_modules*" \
          -x "*attached_assets*" \
          -x "*.local*" \
          -x "*dist/client*"
      
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ github.event.inputs.application_name }}
        environment_name: ${{ github.event.inputs.environment_name }}
        region: us-east-2
        version_label: manual-v${{ github.run_number }}-${{ github.sha }}
        deployment_package: flutterbye-deployment.zip
        wait_for_deployment: false
        use_existing_version_if_available: true